
ANSWER_OF_LIFE = 0x2b

THOMAS_WAYNE_IS_DEAD = False
MARTHA_WAYNE_IS_DEAD = False

BRUCE_WAYNE_IS_A_HAPPY_CHILD = (not THOMAS_WAYNE_IS_DEAD and
                                not MARTHA_WAYNE_IS_DEAD)
BATMAN_EXISTS = not BRUCE_WAYNE_IS_A_HAPPY_CHILD
